more

diff --git a/hypercube_vt/hy_demoRunner b/hypercube_vt/hy_demoRunner
--- a/hypercube_vt/hy_demoRunner
+++ b/hypercube_vt/hy_demoRunner
@@ -1,8 +1,42 @@
 #!/bin/bash -x
 
+############################
+# defaults
+############################
+
 root=/NTFS/Shared/demos
 host=cube
 rhost=$(hostname)
+mono=
+
+############################
+
+
+function usage()
+{
+    cat << EOF
+
+  Usage: $0 [SERVER_HOST][-m|--mono]|[-h|--help]
+
+  Run the hyperCube demoRunner.
+
+
+          OPTIONS
+
+
+    -h|--help      Print this help and exit
+
+    -m|--mono      Run programs with mono visuals (not stereo)
+                   NOT WRITTEN YET  need env DEMORUNNER_OPTIONS
+
+    SERVER_HOST    Run the nodejs demoRunner server on SERVER_HOST.
+                   That's for testing.
+
+EOF
+
+    exit 1
+}
+
 
 function catch()
 {
@@ -15,6 +49,7 @@ function catch()
 
 function runServer()
 {
+
     ssh $host -X\
  demoRunner-server $root\
  --remote $rhost\
@@ -24,8 +59,30 @@ function runServer()
  --heading \"HyperCube Demos\"
 }
 
-if [ ! -d $root ] ; then
+
+# I guess this assumes that you are using a bash shell on $host
+if ssh $host "if [ -d $root ] ; then exit 0 ; fi ; exit 1" ; then
     root=/usr/local/src/demoRunner/testDocRoot
+fi
+
+
+while [ -n "$1" ] ; do
+    case "$1" in
+        -*)
+            usage
+            ;;
+        *)
+            host=$1
+            ;;
+    esac
+    shift 1
+done
+
+if ! gar_pushSshKeys $host ; then
+    echo
+    echo "FAILED to check ssh keys"
+    echo
+    exit 1
 fi
 
 runServer &
@@ -55,3 +112,4 @@ firefox http://$host:8080/
 while [ -n "$server" ] ; do
     wait $server
 done
+
