fixed starting x in hy_start

diff --git a/hypercube_vt/hy_start b/hypercube_vt/hy_start
--- a/hypercube_vt/hy_start
+++ b/hypercube_vt/hy_start
@@ -28,6 +28,18 @@ EOF
     exit 1
 }
 
+function Fail()
+{
+    if [ -n "$1" ] ; then
+        echo
+        echo "$*"
+        echo
+    fi
+
+    echo "$0 failed"
+    exit 1
+}
+
 function Run()
 {
     echo "$*"
@@ -76,7 +88,6 @@ Run hy_kill_dtk-server
 Run hy_projectors_on $mono
 
 Run hy_startx
-displaySave="$DISPLAY"
 
 # We check that we are running xfce4-session and we can connect
 # to the X server and then check that xfce4-session is
@@ -99,29 +110,6 @@ EOF
     fi
 done
 
-# test that a particular X server is running
-# startx may have failed or not finished starting yet
-# so we test it here with xset
-display=":0.15"
-export DISPLAY=$display
-
-count=0
-while ! xset -q > /dev/null ; do
-    echo "Failed ($count seconds) to run a good X session yet."
-    let count=$count+1
-    if [ $count = 40 ] ; then
-        cat <<EOF
- Failed ($count seconds) $count tries to connect to X server at DISPLAY=$DISPLAY
-
-EOF
-        exit 1
-    fi
-    sleep 1
-done
-# We confirmed that we can connect to this X server.
-echo "found a good X server at DISPLAY=$display"
-[ -n "$displaySave" ] && export DISPLAY="$displaySave"
-
 # Make sure that the xfce4-session is still running. We have seen xfce4-session
 # fail to be running at this point; strange but true.
 count=0
@@ -136,6 +124,20 @@ EOF
 	exit 1
     fi
 done
+
+displaySave="$DISPLAY"
+
+# Check all 16 X displays.  Sometimes just one fails.
+for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ; do
+    # This checks and waits for X to draw a widget with a GTK+ window.
+    echo "DISPLAY=:0.$i hy_checkXRunning --sync"
+    DISPLAY=:0.$i hy_checkXRunning --sync ||\
+ Fail "cannot run GTK+ program on DISPLAY=:0.$i"
+done
+
+# We confirmed that we can connect to this X server.
+echo "found a good X server at DISPLAY=$display"
+[ -n "$displaySave" ] && export DISPLAY="$displaySave"
 
 
 
