Fix hy_stopx so it just kill -9 X

diff --git a/hypercube_vt/hy_start b/hypercube_vt/hy_start
--- a/hypercube_vt/hy_start
+++ b/hypercube_vt/hy_start
@@ -8,10 +8,9 @@ function usage()
 
   Run many programs needed to start a HyperCube session.
 
-  Runs the following 6 programs:
+  Runs the following 5 programs:
 
     hy_stopx                   makes sure no user X sessions are running
-    hy_kill_dtk-server         kill any dtk-server
     hy_projectors_on [--mono]  turn on projects
     hy_startx                  start a user login X session
     hy_edgeBlend_on            fade the edges of overlapping root windows
@@ -19,9 +18,6 @@ function usage()
     hy_syncToVBlank_on         turn on nvidia sync to verticle refresh
 
   By default we turn on the projector for stereo display, not --mono.
-  This program does not start dtk-server, given that you, in general,
-  do not want it running and it may even conflict with what you may
-  want to do.
 
 EOF
 
@@ -78,8 +74,6 @@ done
 # be running anymore and so this could hang
 # forever.
 Run hy_stopx
-# then kill any old DTK servers
-Run hy_kill_dtk-server
 
 
 
@@ -124,26 +118,27 @@ sleep 0.6
 WaitForXProgramsToBeRunning
 
 
-# Interesting idea, but it fails to
+# Interesting idea, but it fails ??????
+# Trying to remove this block of code.
 # this must be the same file as in hy_startx.c
-tmpfile=/tmp/XzzX_hy_xsessionCheck
-count=0
+#tmpfile=/tmp/XzzX_hy_xsessionCheck
+#count=0
 # We installed /etc/xdg/autostart/hy_checkX11Session.desktop as a signaler
 # which we hope to have create $tmpfile when the xfce session is
 # started.
-while [ ! -e $tmpfile ] ; do
-    echo "Waiting ($count seconds) for $tmpfile to exist"
-    sleep 1
-    let count=$count+1
-    if [ $count = 40 ] ; then
-                cat <<EOF
- Failed ($count seconds) to find $prog running
-
-EOF
-        exit 1
-    fi
-done
-echo "Found file $tmpfile"
+#while [ ! -e $tmpfile ] ; do
+#    echo "Waiting ($count seconds) for $tmpfile to exist"
+#    sleep 1
+#    let count=$count+1
+#    if [ $count = 40 ] ; then
+#                cat <<EOF
+# Failed ($count seconds) to find $prog running
+#
+#EOF
+#        exit 1
+#    fi
+#done
+#echo "Found file $tmpfile"
 
 
 displaySave="$DISPLAY"
