fixxing startx and stopx

diff --git a/hypercube_vt/hy_startx b/hypercube_vt/hy_startx
--- a/hypercube_vt/hy_startx
+++ b/hypercube_vt/hy_startx
@@ -1,6 +1,16 @@
 #!/bin/bash
 
-# TODO: run in foreground or background?
 set -x
-startx &
-#startx
+
+# We run only one startx and we setup a PID file so that
+# we may signal it via hy_stopx
+
+pid_file=${HOME}/.hy_pidfile
+exec 6 > $pid_file || exit 1
+flock -x -n 6 || exit 1 # only one process at a time from here
+echo "$$" 1>&6
+# if this bash process is signaled it should pass on the
+# signal to the startx child process that we run next.
+startx
+rm -f $pid_file
+# now the next process may continue if it did not fail
diff --git a/hypercube_vt/hy_stopx b/hypercube_vt/hy_stopx
--- a/hypercube_vt/hy_stopx
+++ b/hypercube_vt/hy_stopx
@@ -1,8 +1,13 @@
 #!/bin/bash
 
-# TODO: This does not work. Rewrite using a PID file from startx  
+pid_file=${HOME}/.hy_pidfile
+if [ ! -f $pid_file ] ; then
+    echo "PID file \"$pid_file\" not found"
+    exit 1
+fi
+
+pid="$(cat $pid_file)"
 set -x
-# get DBUS_SESSION_BUS_ADDRESS
-source ${HOME}/.cache/upstart/dbus-session
-export DBUS_SESSION_BUS_ADDRESS
-xfce4-session-logout --logout --display=:0.0
+kill -INT $pid
+# The hy_start script will clean up the pid file
+
